### PR TITLE
Travis updates, ruby 2.2, head (allowed to fail) and gitter notification

### PR DESCRIPTION
**Pull request by smathy**
Someone with write access will need to go to gitter to get the URL, you go here and click on Travis and grab the URL
skitch

### CODE REVIEW

**Comment by smathy** [comment]
This failure is fixed by #338

**Comment by apotonick** [comment]
Thanks!!!

Not a huge fan of the gitter integration... you get blasted with "apotonick pushed this, apotonick pushed that", dunno..

**Comment by smathy** [comment]
Oh right, I didn't realize it was so different for the webhooks.  We can configure that though. Something like this:

```yaml
  on_success: change
  on_failure: always
  on_start: never
```

Will notify of all failures, of first success after failure.

NB, what you merged already had [the webhook placeholder in the `.travis.yml`](https://github.com/apotonick/cells/blob/master/.travis.yml#L20-L22) (although not doing any damage, it'll probably be an error inside Travis somewhere).

**Comment by timoschilling** [comment]
@apotonick has forgotten to set the api key into the travis file, thats way it has no effect.

**Comment by timoschilling** [comment]
@apotonick you should set the key or remove the webhook, I vote for the last option

**Pull request merged**
