### PR TITLE
Add tests for assets_paths option

### PR DESCRIPTION
**Pull request by opti**
Per discussion on #303 here are some tests for possible `assets_paths` option implementation.

Use cases:

#### Defaults

```ruby
class SongCell < Cell::ViewModel
  # app/cells/song/
end

class Song::Cell < Cell::Concept
  # app/concepts/song/views
end
```

#### Definition

```ruby
class SongCell < Cell::ViewModel
  self.assets_paths = ["assets"]
  # app/cells/song/assets
end

class Song::Cell < Cell::Concept
  self.assets_paths = ["assets"]
  # app/concepts/song/assets
end

class Song::Cell < Cell::Concept
  self.assets_paths << "assets"
  # app/concepts/song/views
  # app/concepts/song/assets
end
```

It's an open question: should the paths be relative to controller_path or can be global.

### CODE REVIEW

**Comment by apotonick** [comment]
If they want them global, we can add that functionality later. E.g. by providing `asset_paths = "/var/assets"`.

In Defaults, that should say

```ruby
class Song::Cell < Cell::Concept
  # app/concepts/song/views
end
```

right?

**Comment by opti** [comment]
> In Defaults, that should say

You're right. It's how things now. I'll update

**Comment by opti** [comment]
Initial description updated as well

**Comment by opti** [comment]
Closing since the main issue [has been fixed](https://github.com/apotonick/cells/issues/303#issuecomment-216428268).

**Pull request closed without merging**
